import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {NavBar} from "@/components/NavBar";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <html lang="en">
      <body>
      <NavBar />
      {children}
      </body>
      </html>
  );
}

